---
version: "3"

tasks:
  default: 
    cmd: task --list --sort none
    silent: true

includes: 
  machines:
    silent: true
    taskfile: taskfiles/machines.yaml

  brew:
    silent: true
    taskfile: taskfiles/homebrew.yaml
